[package]
name = "mimo-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
tower-http = "0.6.6"
